2025-05-08 02:03:57,086 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-08 02:06:40,314 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-08 02:07:07,211 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-08 02:11:47,956 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-08 02:12:50,437 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-08 02:13:27,708 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-08 02:13:33,738 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-08 13:11:46,018 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /
2025-05-08 13:11:46,145 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /favicon.ico
2025-05-08 13:20:54,082 [ERROR] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Internal Server Error: /works/create_author_work
Traceback (most recent call last):
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ~~~~~~~~~~~~~~~^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 134, in form_valid
    return super().form_valid(form)
           ~~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ~~~~~~~~~~~~~~~~~~~~^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\views\generic\edit.py", line 119, in get_success_url
    if self.success_url:
       ^^^^^^^^^^^^^^^^
  File "D:\code\oquArna\.venv\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\code\oquArna\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'author-works' with no arguments not found. 1 pattern(s) tried: ['works/author_works/(?P<category>[0-9]+)\\Z']
2025-05-08 13:22:11,437 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /works/download_author_work/3
2025-05-08 13:24:47,266 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /works/download_author_work/3/
2025-05-08 13:24:50,229 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /works/download_author_work/3
2025-05-08 13:27:36,158 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /works/download_author_work/3
2025-05-08 13:28:35,063 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /works/download_author_work/4
2025-05-08 13:29:38,483 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /works/download_author_work/3
2025-05-08 13:33:26,392 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-08 13:41:14,907 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-08 16:02:24,501 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /
2025-05-08 16:02:24,519 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /
2025-05-08 16:02:24,656 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /favicon.ico
2025-05-08 16:02:24,662 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /favicon.ico
2025-05-08 16:02:32,785 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /works/
2025-05-08 18:20:46,561 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /favicon.ico
2025-05-08 18:31:29,060 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-05-08 22:25:03,635 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /
2025-05-08 22:25:03,815 [WARNING] django.request D:\code\oquArna\.venv\Lib\site-packages\django\utils\log.py:248
Not Found: /favicon.ico
